### ISSUE TITLE
Movz and movn problem after branches

### ISSUE THREAD

**Issue by jimger** [lupino3/edumips64#63]
Hey. The program has unexpected behaviour when it finds the movn and movz instructions after having branch or jump. It takes the instructions into the pipeline but doesn't do the move even though the condition is true. I am not talking only exactly after branch or jump. I am talking if generally I have branch that is taken then move instructions stop working correctly

**Comment by lupino3** [comment]
Hello, and thanks for the bug report.

Unfortunately, I am unable to reproduce it. I have created a sample program:

            .code
  
            DADDI r1, r0, 1   ; Put the number 1 in R1.
    branch: BNEZ r0, branch   ; Will never be taken.
            MOVZ r2, r1, r0   ; If r0 is 0 (always) move the contents of r1 in r2.
            HALT

The program has a `MOVZ` instruction right after a branch. The branch is not taken.

As you can see in the following screenshot, at the end of the code the register `r2` contains the value `1`, which means that the `MOVZ` instruction was executed.

![screenshot from 2016-04-16 18 59 57](https://cloud.githubusercontent.com/assets/200139/14582749/7fd07102-0405-11e6-9b39-fbf9181e042c.png)

Do you have a program which shows the bug?

Thanks,
Andrea

**Comment by jimger** [comment]
Hey Andrea,
Yes take these files
run the min max and just place the other files at the same folder.
This is a simple program that finds the min and max of each set and writes the min at the first 5 places of each set and the max at the other 5. The normal algorithm finishes at line 48 I think. Because it wasn’t working as it supposed I copied the algorithm 2 more times. So we have 3x times the algorithm. Then look at the bne at line 135. This is the branch that checks the loop. After the branch the algorithm stops working right. It does the load. But doesn’t do the move. Look at the results. set00-set02 are right. set 03 is a bit strange. set 04+ have the first value for min value and previous max as max

**Comment by lupino3** [comment]
Hi, I don't see the attachment. Did you add them to the comment? Thanks!

**Comment by jimger** [comment]
I responded to email with the attachments…. Probably I couldn’t do that :P
I uploaded them to dropbox

https://www.dropbox.com/s/ivqugca3eznm7rg/edumips.zip?dl=0

Thanks

**Comment by lupino3** [comment]
I have tried to reproduce the bug and indeed it seems that `MOVN` and `MOVZ` are not executed after the branch in your program is taken.

The program is long, so it might or might not be directly caused by the branch. I will have more time to work on this issue during the weekend. Thanks for the report!

**Comment by jimger** [comment]
No problem… Just to help you, the program has 3 times the same program. This was to prove to me and to you that the algorithm works. Real program stops at line 48 and after this just put line 135 bne r2,r3,start_min_max.
You can erase the rest.

Thanks anyway

**Comment by lupino3** [comment]
Hello,
I finally had some time to look a bit more closely to this bug report, and I believe that the simulator is working correctly.

To test it, I took your example files, and as you suggested I put `BNE r2, r3, start_min_max` at line 135. Now, immediately before that, I put a `BREAK` instruction, which will be useful to examine the behavior cycle-by-cycle. I have repackaged everything in the attached zip file.

To see that the instructions are working correctly, open `min_max.s` and press `F4` to get to the `BREAK` instruction (cycle 60). Now advance by 8 cycles with `F7`, to get to the interesting part (cycle 68).

The `MOVN` instruction at address `0x14` is about to execute the `EX` stage. The predicate is `t8 == 1`, and the value of `t8` is `1`. If the code were broken, nothing should happen. If you press `F7`, you'll instead see that the value of `s8` changes to `0x2CA`, because of `MOVN`. It works. :)

Now there is the `MOVZ` instruction at address `0x14` in the EX stage. `t8` is still 1, so it will not cause any changes. Pressing `F7` will advance one cycle and indeed no register changes value.

Finally, there is another `MOVN` in the `EX` stage. This one is predicated on `t8 == 1`, which is true. So `s0` should change to the value of `t0`, which is exactly what happens.

Therefore I don't think there are any problems in the behavior of the simulator. Please try the example yourself and let me know if you agree with my analysis. If it still doesn't seem to work, please let me know and I'll investigate more.

Thanks,
Andrea

[mov-works-example.zip](https://github.com/lupino3/edumips64/files/275987/mov-works-example.zip)

**Comment by jimger** [comment]
Hi Andrea,
I will check it further on Friday

Thanks,
Dimitris
